language: python
python: 2.7

matrix:
  include:
    - python: 2.7
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py migrate
services:
  - postgresql

addons:
  postgresql: "9.5"
